# Generated by Django 4.2.3 on 2024-08-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', max_length=10)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged In Users'), ('admin_only', 'Admin Only')], default='public', max_length=20)),
            ],
        ),
    ]
